import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {githubApi,allPages} from './lib/github.mjs';
import {canPublish} from './lib/approval.mjs';
import {submissionHash} from './lib/issue-content.mjs';
import {readData} from './publish-issue.mjs';
import {contentHash,collections,deletionLabel,deletionPayload} from '../server/content-identity.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export function verifyDeletion(snapshot,current,actorPermission,authorPermission) {
  if(!canPublish(actorPermission)||!canPublish(authorPermission))throw new Error('只有仓库维护者可以发起和执行删除。');
  if(snapshot.pull_request||current.pull_request||snapshot.number!==current.number||current.state!=='open')throw new Error('删除请求已关闭或无效。');
  if(!current.labels?.some(label=>(label.name || label)===deletionLabel))throw new Error('删除标签已移除。');
  if(submissionHash(snapshot)!==submissionHash(current))throw new Error('删除请求已被修改，请重新确认。');
  const payload=deletionPayload(current.body);
  if(payload.userId!==current.user?.id)throw new Error('删除请求的发起人不匹配。');
  return payload;
}
export function prepareDeletion({directory,issue,reviewer,date=new Date().toISOString()}) {
  const payload=deletionPayload(issue.body),{type,id,hash}=payload;
  const auditPath='content/deletions/'+type+'--'+id+'.json',auditFile=path.join(directory,auditPath);
  const data=readData(directory),collection=collections[type],item=data[collection].find(item=>item.id===id);
  if(!item) {
    if(fs.existsSync(auditFile))return {changed:false,type,id,files:[]};
    throw new Error('没有找到要删除的内容。');
  }
  if(contentHash(item)!==hash)throw new Error('内容在确认后已更新，请刷新网站后重新发起删除。');
  const discussionFile=path.join(directory,'dist/discussions.js'),context={window:{}};
  vm.runInNewContext(fs.readFileSync(discussionFile,'utf8'),context,{timeout:1000,contextCodeGeneration:{strings:false,wasm:false}});
  const discussions=context.window.CAMPUS_DISCUSSIONS;
  const discussion=discussions.items[type+':'+id];
  delete discussions.items[type+':'+id];
  data[collection]=data[collection].filter(item=>item.id!==id);
  data.updatedAt=new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Sydney',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(date));
  fs.mkdirSync(path.dirname(auditFile),{recursive:true});
  fs.writeFileSync(auditFile,JSON.stringify({type,id,hash,issue:issue.number,deletedBy:reviewer,deletedAt:date,discussion},null,2)+'\n');
  fs.writeFileSync(path.join(directory,'dist/data.js'),'// Content is maintained through reviewed GitHub submissions and repository changes.\nwindow.CAMPUS_DATA = '+JSON.stringify(data,null,2)+';\n');
  fs.writeFileSync(discussionFile,'// Generated by scripts/sync-discussions.mjs. Keep stable content IDs.\nwindow.CAMPUS_DISCUSSIONS = '+JSON.stringify(discussions,null,2)+';\n');
  return {changed:true,type,id,files:['dist/data.js','dist/discussions.js',auditPath]};
}
async function report(api,number,message,label) {
  await api('/issues/'+number+'/labels',{method:'POST',body:{labels:[label]}});
  const marker='<!-- usyd-delete-result:'+label+' -->';
  if(!(await allPages(api,'/issues/'+number+'/comments')).some(item=>item.body?.includes(marker)))await api('/issues/'+number+'/comments',{method:'POST',body:{body:marker+'\n\n'+message}});
}
export async function deleteContent({directory=root,event,repository,token,actor,api=githubApi(repository,token),gitRunner,argsRunner}={}) {
  const number=Number(event.issue?.number || event.inputs?.issue_number);
  if(!Number.isSafeInteger(number)||number<1||!/^[-a-zA-Z0-9]+$/.test(actor || '')||event.repository?.full_name!==repository)throw new Error('删除事件无效。');
  const snapshot=event.issue || await api('/issues/'+number);
  const git=gitRunner || ((...args)=>execFileSync('git',args,{cwd:directory,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim());
  const run=argsRunner || ((...args)=>execFileSync(process.execPath,args,{cwd:directory,stdio:'inherit'}));
  const verify=async()=>verifyDeletion(snapshot,await api('/issues/'+number),await api('/collaborators/'+encodeURIComponent(actor)+'/permission'),await api('/collaborators/'+encodeURIComponent(snapshot.user.login)+'/permission'));
  await verify();
  let pushed=false,result;
  try {
    for(let attempt=0;attempt<4;attempt++) {
      await verify();git('fetch','--no-tags','origin','main');git('reset','--hard','origin/main');
      result=prepareDeletion({directory,issue:snapshot,reviewer:actor});
      if(!result.changed){pushed=true;break;}
      run('scripts/check-content.mjs');run('--test','server/*.test.mjs','tests/*.test.mjs');
      await verify();git('add','--',...result.files);
      git('-c','user.name=github-actions[bot]','-c','user.email=41898282+github-actions[bot]@users.noreply.github.com','commit','-m','Remove content from deletion request #'+number);
      await verify();
      try{git('push','origin','HEAD:main');pushed=true;break;}catch{if(attempt===3)throw new Error('仓库有并发更新，请重新运行删除任务。');}
    }
    await report(api,number,'已从网站数据中删除 `'+result.type+':'+result.id+'`。部署完成后，列表和详情页将不再显示。原投稿和讨论记录保留在 GitHub。','已删除');
    await api('/actions/workflows/ci.yml/dispatches',{method:'POST',body:{ref:'main'}});
    return result;
  } catch(error) {
    if(!pushed)await report(api,number,'删除未完成：'+(error.status?'GitHub 请求失败，请重试。':String(error.message).slice(0,400)),'删除失败').catch(()=>{});
    throw error;
  }
}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href) {
  if(process.env.GITHUB_ACTIONS!=='true')throw new Error('删除命令仅在 GitHub Actions 的临时检出目录中运行。');
  const event=JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH,'utf8'));
  await deleteContent({event,repository:process.env.GITHUB_REPOSITORY,token:process.env.GITHUB_TOKEN,actor:event.sender?.login || process.env.GITHUB_ACTOR});
}
